<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE biblioteca [
  <!ELEMENT biblioteca (libro+, piepagina)>
  <!ELEMENT libro (titulo, portada, autor, resumen)>
  <!ELEMENT titulo (#PCDATA)>
  <!ELEMENT portada EMPTY>
  <!ELEMENT autor (#PCDATA)>
  <!ELEMENT resumen (#PCDATA)>
  <!ATTLIST libro paginas CDATA #REQUIRED>
  <!ATTLIST portada foto CDATA #REQUIRED>
  <!ELEMENT piepagina (p)>
  <!ELEMENT p (#PCDATA)>
]>

<biblioteca>
  <libro paginas="192">
    <titulo>Cartero</titulo>
    <portada foto=""/>
    <autor>Charles Bukowski</autor>
    <resumen>
      En Cartero, Charles Bukowski describe los doce años en que estuvo empleado 
      en una sórdida oficina de correos de Los Ángeles. 
      El libro termina cuando Chinaski/Bukowski abandona la miserable seguridad 
      de su empleo, a los 49 años, para dedicarse exclusivamente a escribir. 
      Y escribe Cartero, su primera novela.
    </resumen>
  </libro>

  <libro paginas="200">
    <titulo>Pulp</titulo>
    <portada foto="pulp"/>
    <autor>Charles Bukowski</autor>
    <resumen>
    En Los Ángeles corre un rumor muy extraño. Se dice que un tal Céline, que merodea 
    por las librerías inspeccionando a la competencia y buscando primeras ediciones de 
    Faulkner, sería nada más ni nada menos que Louis Ferdinand, que no habría muerto en
    1961 en Meudon. Nick Belane, un detective privado muy poco intelectual, es el encargado
    de averiguar la verdad. ¿Y quién quiere saberla? Una dama muy fatal, quizá la más fatal
    de todas, que no acepta que Céline pudiera haber escapado a su mortal encanto. Pero de
    repente la temporada de trabajo se ha vuelto muy buena para Nick y tiene varios asuntos
    más entre manos: encontrar el Gorrión Rojo, que no es el nieto del Halcón Maltés para un 
    tal John Barton, y descubrir si Cindy, la mujer de Jack Bass, engaña a su marido. Pero, como
    ya demostró cumplidamente Raymond Chandler, todos los casos de un detective siempre se lían 
    entre sí, y entre Cindy y Céline se organizará un lío considerable.
    </resumen>
  </libro>

  <libro paginas="500">
    <titulo>La Danza de la muerte</titulo>
    <portada foto="danza"/>
    <autor>Douglas Preston y Lincoln Child</autor>
    <resumen>
    Tras la supuesta muerte del inspector Pendergast, enfrentado a su malvado hermano Diógenes
    (La mano del diablo), el detective D'Agosta cumple las instrucciones de Pendergast: detener
    a Diógenes, que ha anunciado la comisión inminente de un espectacular crimen. Pendergast, 
    amparado por su propia muerte, ha de moverse deprisa y con gran riesgo para tender una trampa
    a su hermano: tendrá que convertirse en ladrón si quiere atraparlo.
    </resumen>
  </libro>

  <libro paginas="528">
    <titulo>Los Asesinatos de Manhattan</titulo>
    <portada foto="manhattan"/>
    <autor>George Orwell</autor>
    <resumen>
    Durante los trabajos de excavación para construir un nuevo bloque de apartamentos en Manhattan,
    los obreros hacen un descubrimiento espeluznante: los restos de treinta y seis personas torturadas
    y mutiladas, víctimas de un asesino que aterrorizó a la ciudad de Nueva York a finales del XIX.

    El agente especial Pendergast del FBI convence a Nora Kelly, arqueóloga del Museo de Historia Natural,
    de que le ayude a resolver el misterio de aquellas muertes. Pero lo que era solo una inquietante
    investigación histórica se convierte en la caza desesperada de un cruel asesino, cuando sobre la
    ciudad se abate una oleada de asesinatos casi idénticos a los de un siglo atrás.
    </resumen>
  </libro>

  <piepagina>
    <p>sara mh</p>
  </piepagina>
</biblioteca>
