=== e51894d/Lenguajes2024Sara_Mulero/segundotrimestre/ejerciciosXML/tema_10/ejercicio8/gestioncurso.dtd
<!ELEMENT gestion (alumno+)>
<!ELEMENT alumno (nombre, apellidos, curso, asignaturas)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT curso (#PCDATA)>
<!ELEMENT asignaturas (asignatura+)>
<!ELEMENT asignatura (nombre, trimestre1, trimestre2, trimestre3)>
<!ELEMENT trimestre1 (#PCDATA)>
<!ELEMENT trimestre2 (#PCDATA)>
<!ELEMENT trimestre3 (#PCDATA)>

=== e51894d/Lenguajes2024Sara_Mulero/segundotrimestre/ejerciciosXML/ejercicio8/gestioncurso.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gestion SYSTEM "gestioncurso.dtd">
<gestion>
    <alumno>
        <nombre>Carlos</nombre>
        <apellidos>Hurtado Cánovas</apellidos>
        <curso>2º DAW</curso>
        <asignaturas>
            <asignatura>
                <nombre>Programación</nombre>
                <trimestre1>8.5</trimestre1>
                <trimestre2>7.8</trimestre2>
                <trimestre3>9.2</trimestre3>
            </asignatura>
            <asignatura>
                <nombre>Bases de Datos</nombre>
                <trimestre1>7.0</trimestre1>
                <trimestre2>8.0</trimestre2>
                <trimestre3>8.5</trimestre3>
            </asignatura>
        </asignaturas>
    </alumno>
</gestion>
