<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/css" href="index.css"?>


<!DOCTYPE biblioteca [
  <!ELEMENT biblioteca (libro+, piepagina)>
  <!ELEMENT libro (titulo, portada, autor, resumen)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT portada (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT resumen (#PCDATA)>
  <!ATTLIST libro paginas CDATA #REQUIRED>
  <!ATTLIST portada foto CDATA #REQUIRED>

  <!--pie de pág-->
  <!ELEMENT piepagina (p)>
  <!ELEMENT p (#PCDATA)>
]>

  <!--biblioteca-->
<biblioteca>
  <!--libro1-->
  <libro paginas="192">
    <titulo>Cartero</titulo>
    <portada foto="carteroportada"></portada>
    <autor>Charles Bukowski</autor>
    <resumen>
      En Cartero, Charles Bukowski describe los doce años en que estuvo empleado 
      en una sórdida oficina de correos de Los Ángeles. 
      El libro termina cuando Chinaski/Bu­kowski abandona la miserable seguridad 
      de su empleo, a los 49 años, para dedicarse exclusivamente a escribir. 
      Y escribe Cartero, su primera novela.
    </resumen>
  </libro>

  <!--libro2-->
  <libro paginas="300">
    <titulo>El Significado de la Cábala</titulo>
    <portada foto="kabbalah"></portada>
    <autor>Leo Schaya</autor>
    <resumen>
      "El Significado Universal de la Cábala" es una obra esencial para quienes buscan entender las enseñanzas profundas y espirituales que se encuentran en la Cábala, un sistema místico y filosófico que ha influenciado profundamente tanto a la religión judía como a otras tradiciones espirituales. Leo Schaya presenta una visión integral de la Cábala, explicando sus conceptos clave y su aplicación en la vida cotidiana.

      El libro examina la estructura del Árbol de la Vida, un diagrama simbólico que representa las fuerzas divinas que actúan en el mundo y en el alma humana. Schaya explica cómo la Cábala no solo es una doctrina religiosa, sino también un sistema filosófico que busca la comprensión de la relación entre el hombre y lo divino. A través de una serie de meditaciones y estudios simbólicos, el autor ayuda al lector a entender cómo las enseñanzas cabalísticas pueden ser aplicadas para alcanzar un mayor entendimiento de uno mismo y del universo.

      La obra también incluye un análisis de los principales textos cabalísticos, como el Zohar, y presenta la Cábala como una vía de conocimiento directo que permite al individuo trascender la realidad material y conectar con la fuente divina. Schaya aborda cómo la Cábala ha influenciado no solo la espiritualidad judía, sino también a figuras clave del pensamiento occidental, desde los filósofos hasta los místicos.
    </resumen>
  </libro>

  <!--libro3-->
  <libro paginas="500">
    <titulo>Libro de la Sabiduría Vol. II</titulo>
    <portada foto="sabiduria"></portada>
    <autor>Revival of Wisdom</autor>
    <resumen>
      El "Libro de la Sabiduría Vol. II" es una obra esotérica que profundiza en los misterios espirituales universales, ofreciendo una comprensión profunda sobre la conexión entre la conciencia humana y el cosmos. Este volumen continúa el legado de sabiduría ancestral, basado en enseñanzas de antiguos místicos, filósofos y sabios que han transmitido conocimientos ocultos a lo largo de los siglos.

      A través de sus páginas, se exploran conceptos fundamentales como la energía universal, el propósito de la vida, la meditación y la trascendencia del ser humano hacia un estado de conciencia superior. Los capítulos abordan la ciencia espiritual, las leyes cósmicas y la evolución del alma, brindando herramientas prácticas y ejercicios para la expansión de la conciencia, la transformación interior y el acceso a una comprensión más profunda del universo. Además, el autor ofrece una visión sobre la sabiduría oculta presente en las culturas antiguas, con el objetivo de conectar al lector con su sabiduría interior y alcanzar un nivel de entendimiento trascendental.
    </resumen>
  </libro>

  <!--libro4-->
  <libro paginas="342">
    <titulo>1984</titulo>
    <portada foto="1984"></portada>
    <autor>George Orwell</autor>
    <resumen>
      "1984" es una obra maestra de la literatura distópica que describe un futuro totalitario y opresivo donde el gobierno, conocido como el Partido, controla cada aspecto de la vida de los ciudadanos. En la sociedad descrita en el libro, el concepto de "libertad" ha desaparecido, y la vigilancia constante a través de dispositivos como el "telepantalla" es la norma.

      El protagonista, Winston Smith, es un miembro del Partido que trabaja en el Ministerio de la Verdad, donde se encarga de reescribir la historia para que coincida con la narrativa oficial del régimen. A medida que Winston se rebela internamente contra la opresión, busca la verdad y se enamora de Julia, su compañera en la resistencia. Sin embargo, el Partido tiene el control total sobre la mente humana, y la "doble verdad" y la "neolengua" son herramientas utilizadas para manipular el pensamiento.

      La novela examina temas como la represión, la vigilancia, la manipulación de la verdad y la importancia de la privacidad en una sociedad libre. "1984" es una crítica mordaz a los regímenes totalitarios y una reflexión profunda sobre los peligros de perder la autonomía en un mundo cada vez más controlado.
    </resumen>
  </libro>

  <!--pie de pag-->
  <piepagina>
    <p>sara mh</p>
  </piepagina>
</biblioteca>