=== e51894d/Lenguajes2024Sara_Mulero/segundotrimestre/ejerciciosXML/tema_10/ejercicio3/menu.dtd
<!ELEMENT menu (item+)>
<!ELEMENT item (nombre, precio, tipo, categoria)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ATTLIST precio moneda CDATA #REQUIRED>
<!ELEMENT categoria (#PCDATA)>

=== e51894d/Lenguajes2024Sara_Mulero/segundotrimestre/tema_10/ejercicio3/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "menu.dtd">
<menu>

    <item>
        <nombre>Mazamorra</nombre>
        <precio moneda="EUR">8.50</precio>
        <tipo>Entrante</tipo>
        <categoria>Crema</categoria>
    </item>

    <item>
        <nombre>Ensalada Jerk</nombre>
        <precio moneda="EUR">12.00</precio>
        <tipo>Primer Plato</tipo>
        <categoria>Ensalada</categoria>
    </item>

    <item>
        <nombre>Fabada</nombre>
        <precio moneda="EUR">17.00</precio>
        <tipo>Segundo Plato</tipo>
        <categoria>Guiso</categoria>
    </item>

    <item>
        <nombre>Helado matcha</nombre>
        <precio moneda="EUR">4.00</precio>
        <tipo>Postre</tipo>
        <categoria>Postre</categoria>
    </item>
</menu>
