=== e51894d/Lenguajes2024Sara_Mulero/segundotrimestre/ejerciciosXML/ejercicio4/datos.dtd
<!ELEMENT documento (datos)>
<!ELEMENT datos (nombre, dni, informacion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT informacion (nombre, dni, fechanac, direccion, ciudad, sexo)>
<!ELEMENT fechanac (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT validez (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>

=== e51894d/Lenguajes2024Sara_Mulero/segundotrimestre/tema_10/ejercicio4/datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE documento SYSTEM "datos.dtd">
<documento>
    <datos>
        <nombre>Elena Jurado Maestre</nombre>
        <dni>12345678F</dni>
        <informacion>
            <nombre>Elena Jurado Maestre</nombre>
            <dni>12345678F</dni>
            <fechanac>27-07-1997</fechanac>
            <direccion>Calle Antonio Machado 28</direccion>
            <ciudad>Cordoba</ciudad>
            <sexo>Femenino</sexo>
        </informacion>
    </datos>
</documento>
