=== e51894d/Lenguajes2024Sara_Mulero/segundotrimestre/ejerciciosXML/tema_10/ejercicio9/pokemon.dtd
<!ELEMENT pokemon (nombre, pokedex, tipo, genero, estado)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT pokedex (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT estado (habilidades, nivel, fuerza, evolucion?, vida?)>
<!ELEMENT habilidades (#PCDATA)>
<!ELEMENT nivel (#PCDATA)>
<!ELEMENT fuerza (#PCDATA)>
<!ELEMENT evolucion (#PCDATA)>
<!ELEMENT vida (#PCDATA)>

=== e51894d/Lenguajes2024Sara_Mulero/segundotrimestre/ejerciciosXML/ejercicio9/pokemon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pokemon SYSTEM "pokemon.dtd">
<pokemon>
    <nombre>Honchkrow</nombre>
    <pokedex>0430</pokedex>
    <tipo>Siniestro/Volador</tipo>
    <genero>Femenino</genero>
    <estado>
        <habilidades>Insomnio, Afortunado</habilidades>
        <nivel>77</nivel>
        <fuerza>105</fuerza>
        <evolucion>No tiene</evolucion>
        <vida>340</vida>
    </estado>
</pokemon>
