=== e51894d/Lenguajes2024Sara_Mulero/segundotrimestre/ejerciciosXML/ejercicio11/tienda.dtd
<!ELEMENT tiendaonline (producto+)>
  <!ELEMENT producto (nombre, categoria, precio, stock)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT categoria (#PCDATA)>
  <!ELEMENT precio (#PCDATA)>
  <!ELEMENT stock (#PCDATA)>

=== e51894d/Lenguajes2024Sara_Mulero/segundotrimestre/ejerciciosXML/tema_10/ejercicio11/tienda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tiendaonline SYSTEM "tienda.dtd">
<tiendaonline>

    <producto>
        <nombre>Samsung Galaxy Z Flip6</nombre>
        <categoria>Smartphone</categoria>
        <precio>800.00</precio>
        <stock>17</stock>
    </producto>

    <producto>
        <nombre>Lavadora Bolero Cecotec</nombre>
        <categoria>Electronica Hogar</categoria>
        <precio>339.00</precio>
        <stock>40</stock>
    </producto>

    <producto>
        <nombre>Lavadora LG Serie 700</nombre>
        <categoria>Electr√≥nica</categoria>
        <precio>499.00</precio>
        <stock>25</stock>
    </producto>
</tiendaonline>
