=== e51894d/Lenguajes2024Sara_Mulero/segundotrimestre/ejerciciosXML/tema_10/ejercicio5/tarjeta.dtd
<!ELEMENT documento (datos)>
<!ELEMENT datos (titulo, informacion)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT informacion (nombre, numero, validez, credito)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT validez (#PCDATA)>
<!ELEMENT credito (#PCDATA)>

=== e51894d/Lenguajes2024Sara_Mulero/segundotrimestre/tema_10/ejercicio5/tarjeta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE documento SYSTEM "tarjeta.dtd">
<documento>
    <datos>
        <titulo>Tarjeta de Cr√©dito</titulo>
        <informacion>
            <nombre>Sara Ml Hr</nombre>
            <numero>0000-0000-0000-0000</numero>
            <validez>01-2040</validez>
            <credito>7777EUR</credito>
        </informacion>
    </datos>
</documento>
