=== e51894d/Lenguajes2024Sara_Mulero/segundotrimestre/ejerciciosXML/ejercicio12/vuelos.dtd
<!ELEMENT reservas (vuelo+)>
<!ELEMENT vuelo (codigo, aerolinea, origen, destino, fecha, horaSalida, horaLlegada, pasajeros)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT aerolinea (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT horaSalida (#PCDATA)>
<!ELEMENT horaLlegada (#PCDATA)>
<!ELEMENT pasajeros (pasajero+)>
<!ELEMENT pasajero (nombre, dni, asiento, clase)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT asiento (#PCDATA)>
<!ELEMENT clase (#PCDATA)>

=== e51894d/Lenguajes2024Sara_Mulero/segundotrimestre/ejerciciosXML/ejercicio12/vuelos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reservas SYSTEM "vuelos.dtd">

<reservas>
    <vuelo>

        <codigo>FI-5577</codigo>
        <aerolinea>Finnair</aerolinea>
        <origen>España</origen>
        <destino>Japón</destino>
        <fecha>19-02-2025</fecha>
        <horaSalida>20:00</horaSalida>
        <horaLlegada>10:45</horaLlegada>

        <pasajeros>

            <pasajero>
                <nombre>Sara Ml Hr</nombre>
                <dni>12345678-A</dni>
                <asiento>7-B</asiento>
                <clase>Turista</clase>
            </pasajero>

            <pasajero>
                <nombre>Andrés P R</nombre>
                <dni>91011121-B</dni>
                <asiento>7-A</asiento>
                <clase>Turista</clase>
            </pasajero>

        </pasajeros>

    </vuelo>
</reservas>
