=== e51894d/Lenguajes2024Sara_Mulero/segundotrimestre/tema_10/ejercicio7/configuracion.dtd
<!ELEMENT configuracion (informaciongeneral, basededatos)>
<!ELEMENT informaciongeneral (nombre, version, autor)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT basededatos (host, puerto, usuario, contrasena, nombreBD)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT puerto (#PCDATA)>
<!ELEMENT usuario (#PCDATA)>
<!ELEMENT contrasena (#PCDATA)>
<!ELEMENT nombreBD (#PCDATA)>

=== e51894d/Lenguajes2024Sara_Mulero/segundotrimestre/ejerciciosXML/ejercicio7/configuracion.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuracion SYSTEM "configuracion.dtd">

<configuracion>

    <informaciongeneral>
        <nombre>Lenguajes2024_PHM</nombre>
        <version>7.1.0</version>
        <autor>Park Hye Min</autor>
    </informaciongeneral>

    <basededatos>
        <host>localhost</host>
        <puerto>5530</puerto>
        <usuario>admin</usuario>
        <contrasena>1234</contrasena>
        <nombreBD>PHyeMin Database</nombreBD>
    </basededatos>

</configuracion>
